### ISSUE TITLE
platformio error

### ISSUE THREAD

**Issue by BackenTrini** [sgrimee/smarty-reader#7]
Hi,
does anybody may give me hint how to fix this error in platformio ?
It's running on a Mac M1, all the latest software versions, every other project compiles well (own and clones from github).
Thanks.
BT.

> Executing task: platformio run <

Processing d1_mini_pro (platform: espressif8266; board: d1_mini_pro; framework: arduino)
-------------------------------------------------------------------------------------------------
Error: Traceback (most recent call last):
  File "/Users/bt/.platformio/penv/lib/python3.9/site-packages/platformio/__main__.py", line 102, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/Users/bt/.platformio/penv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/bt/.platformio/penv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/bt/.platformio/penv/lib/python3.9/site-packages/platformio/cli.py", line 71, in invoke
    return super().invoke(ctx)
  File "/Users/bt/.platformio/penv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/bt/.platformio/penv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/bt/.platformio/penv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/bt/.platformio/penv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/bt/.platformio/penv/lib/python3.9/site-packages/platformio/run/cli.py", line 142, in cli
    process_env(
  File "/Users/bt/.platformio/penv/lib/python3.9/site-packages/platformio/run/cli.py", line 197, in process_env
    result = {"env": name, "duration": time(), "succeeded": ep.process()}
  File "/Users/bt/.platformio/penv/lib/python3.9/site-packages/platformio/run/processor.py", line 83, in process
    install_project_env_dependencies(
  File "/Users/bt/.platformio/penv/lib/python3.9/site-packages/platformio/package/commands/install.py", line 132, in install_project_env_dependencies
    _install_project_env_libraries(project_env, options),
  File "/Users/bt/.platformio/penv/lib/python3.9/site-packages/platformio/package/commands/install.py", line 225, in _install_project_env_libraries
    spec = PackageSpec(library)
  File "/Users/bt/.platformio/penv/lib/python3.9/site-packages/platformio/package/meta.py", line 143, in __init__
    self._parse(self.raw)
  File "/Users/bt/.platformio/penv/lib/python3.9/site-packages/platformio/package/meta.py", line 250, in _parse
    raw = parser(raw)
  File "/Users/bt/.platformio/penv/lib/python3.9/site-packages/platformio/package/meta.py", line 275, in _parse_requirements
    self.requirements = tokens[1].strip()
  File "/Users/bt/.platformio/penv/lib/python3.9/site-packages/platformio/package/meta.py", line 190, in requirements
    else semantic_version.SimpleSpec(str(value))
  File "/Users/bt/.platformio/penv/lib/python3.9/site-packages/semantic_version/base.py", line 647, in __init__
    self.clause = self._parse_to_clause(expression)
  File "/Users/bt/.platformio/penv/lib/python3.9/site-packages/semantic_version/base.py", line 1043, in _parse_to_clause
    return cls.Parser.parse(expression)
  File "/Users/bt/.platformio/penv/lib/python3.9/site-packages/semantic_version/base.py", line 1063, in parse
    raise ValueError("Invalid simple block %r" % block)
ValueError: Invalid simple block '7f1ba48'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq/index.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

The terminal process "platformio 'run'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

**Comment by sgrimee** [comment]
Hi @BackenTrini sorry for the delay. I do not work on this project any more, and I am not planning to because I have not been able to solve the instability issues. I intent to look into a full re-write in Rust on the ESP3s-C3 platform but I don't know if and when I get to it...
